<?php
/**
 * ESTE ARCHIVO NOS PERMITIRÁ SOLICITAR LA CONEXIÓN
 * A NUESTRA BASE DE DATOS, ESTO PARA PODER EJECUTAR CONSULTAS
 * Y LAS SOLICITUDES NECESARIAS PARA OBTENER INFORMACIÓN
*/


//CONEXIÓN A NUESTRO SERVIDOR DE XAMPP
$host = "localhost";
//USUARIO PROPIETARIO QUE ACCEDE A LA BASE DE DATOS
$user = "root";
//CONTRASEÑA PARA INGRESAR A LA BASE DE DATOS
$pass = "";
//NOMBRE DE LA BASE DE DATOS (CAMBIAR DEPENDIENDO EL NOMBRE DE LA BASE DE DATOS)
//EN ESTE CASO LA BASE DE DATOS SE LLAMA GUIA
$dbname = "guia";


//SOLICITUD DE CONEXIÓN A LA BASE DE DATOS
$conn = new mysqli($host, $user, $pass, $dbname);


//SE VERIFICA QUE LA CONEXIÓN A LA BASES DE DATOS SE HAGA CORRECTAMENTE
//DE LO CONTRARIO NOS MUESTRA EL ERROR "Conexión fallida"


if ($conn->connect_error) {
    die("Conexión fallida: " . $conn->connect_error);
}


?>
