<?php

/**
 * ESTE ARCHIVO NOS PERMITIRA SOLICITAR LA CONEXION
 * A NUESTRA BASE DE DATOS, ESTO PARA PODER EJECUTAR CONSULTAS
 * Y LAS SOLICITUDES NECESARIAS PARA OBTENER INFORMACION
*/


//CONEXION A NUEESTRO SERVIDOR DE XAMPP
$host = "localhost";
//USUARIO PROPIETARIO QUE ACCEDE A LA BASE DE DATOS
$user = "root";
//CONTRASEÑA PARA INGRESO A LA BASE DE DATOS
$pass = "";
//NOMBRE DE LA BASE DE DATOS (CAMBIAR DEPENDIENDO EL NOMBRE DE LA BASE DE DATOS)
//EN ESTE CASO LA BASE DE DATOS SE LLAMA GUIA
$dbname = "guia";

//SOLICITUD DE CONEXION A LA BASE DE DATOS
$conn = new mysqli($host, $user, $pass, $dbname);

//SE VERIFICA QUE LA CONEXION A LA BASES DE DATOS SE HAGA CORRECTAMENTE
//DE LO CONTRARIO NOS MUESTRA EL ERROR "Conexión fallida"

if ($conn->connect_error) {
    die("Conexión fallida: " . $conn->connect_error);
}

?>
